[build]
  command = "npm run generate"
  publish = "dist"

[context.branch-deploy.environment]
  NODE_ENV = "development"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[[redirects]]
from = "https://testnet.arcana.network"
to = "https://arcana.network/testnet"
status = 200 
