[build]
  command = "npm run generate"
  publish = "dist"

[context.branch-deploy.environment]
  NODE_ENV = "development"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[[redirects]]
  from = "/blog/*"
  to = "https://blog.arcana.network/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/testnet"
  to = "https://testnet.arcana.network"
  status = 301
  force = true
